server:
  port: 8090
  
spring:
  application:
    name: ${eureka.instance.appname}
    
eureka:
  instance:
    appname: watcher
    
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

turbine:
  #turbine监控的应用名
  app-config: upfront
  cluster-name-expression: new String('default')
  